-- =============================================================================
-- TraceLedger | Layer 1 | 03_validate.sql
-- Sanity checks: row counts and a first look at the injected patterns.
-- =============================================================================

USE WAREHOUSE TRACELEDGER_WH;
USE SCHEMA TRACELEDGER.CORE;

-- 1. Row counts (expected: 16 / 20 / 500 / 629 / 61021 / 140 / 18 / 54 / 229 / 37)
SELECT 'BRANCHES' t, COUNT(*) n FROM BRANCHES UNION ALL
SELECT 'COUNTRY_RISK', COUNT(*) FROM COUNTRY_RISK UNION ALL
SELECT 'CUSTOMERS', COUNT(*) FROM CUSTOMERS UNION ALL
SELECT 'ACCOUNTS', COUNT(*) FROM ACCOUNTS UNION ALL
SELECT 'TRANSACTIONS', COUNT(*) FROM TRANSACTIONS UNION ALL
SELECT 'LOANS', COUNT(*) FROM LOANS UNION ALL
SELECT 'SANCTIONS_LIST', COUNT(*) FROM SANCTIONS_LIST UNION ALL
SELECT 'GROUND_TRUTH', COUNT(*) FROM GROUND_TRUTH UNION ALL
SELECT 'ANALYST_NOTES', COUNT(*) FROM TRACELEDGER.DOCS.ANALYST_NOTES UNION ALL
SELECT 'ADVERSE_MEDIA', COUNT(*) FROM TRACELEDGER.DOCS.ADVERSE_MEDIA;

-- 2. The demo hero: cash deposits just under INR 10L on ACC-1042
SELECT TXN_ID, TXN_TS, AMOUNT, CHANNEL, DESCRIPTION, COUNTERPARTY_NAME, COUNTERPARTY_COUNTRY
FROM TRANSACTIONS
WHERE ACCOUNT_ID = 'ACC-1042'
  AND (AMOUNT BETWEEN 800000 AND 999999 OR AMOUNT >= 1000000)
ORDER BY TXN_TS;

-- 3. Preview of the structuring rule (Layer 2 will formalise this):
--    accounts with >= 3 cash deposits of 8L-9.99L inside a 7-day window
SELECT a.ACCOUNT_ID, COUNT(*) AS deposits_in_window, SUM(b.AMOUNT) AS total_inr
FROM TRANSACTIONS a
JOIN TRANSACTIONS b
  ON b.ACCOUNT_ID = a.ACCOUNT_ID
 AND b.CHANNEL = 'CASH' AND b.DIRECTION = 'CREDIT'
 AND b.AMOUNT BETWEEN 800000 AND 999999
 AND b.TXN_TS BETWEEN a.TXN_TS AND DATEADD(day, 7, a.TXN_TS)
WHERE a.CHANNEL = 'CASH' AND a.DIRECTION = 'CREDIT' AND a.AMOUNT BETWEEN 800000 AND 999999
GROUP BY a.ACCOUNT_ID, a.TXN_ID
HAVING COUNT(*) >= 3
QUALIFY ROW_NUMBER() OVER (PARTITION BY a.ACCOUNT_ID ORDER BY COUNT(*) DESC) = 1
ORDER BY deposits_in_window DESC;

-- 4. Injected typologies (answer key)
SELECT INJECTED_PATTERN, COUNT(*) FROM GROUND_TRUTH GROUP BY 1 ORDER BY 2 DESC;
