-- =============================================================================
-- TraceLedger | Layer 2 | 07_validate_signals.sql
-- How well do the rules find the planted typologies, and what does the
-- explainable score look like?
-- =============================================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE TRACELEDGER_WH;
USE DATABASE TRACELEDGER;
USE SCHEMA SIGNALS;

-- 1. Alerts per rule, with the policy clause each one cites
SELECT a.RULE_ID, ANY_VALUE(a.RULE_NAME) AS RULE_NAME, ANY_VALUE(a.POLICY_REF) AS POLICY_REF,
       COUNT(*) AS N_ALERTS, ROUND(SUM(a.AMOUNT_INR) / 1e7, 2) AS FLAGGED_INR_CRORE
FROM ALERTS a
GROUP BY a.RULE_ID
ORDER BY N_ALERTS DESC;

-- 2. Detection rate against the answer key (each planted pattern -> the rule meant to catch it)
WITH expected AS (
  SELECT * FROM (VALUES
    ('STRUCTURING', 'TM-STR'), ('VELOCITY_SPIKE', 'TM-VEL'), ('DORMANT_REACTIVATION', 'TM-DOR'),
    ('HIGH_RISK_GEOGRAPHY', 'TM-GEO'), ('INCOME_MISMATCH', 'TM-INC'), ('ROUND_AMOUNTS', 'TM-RND'),
    ('RAPID_IN_OUT', 'TM-RIO'), ('MULE_RING', 'TM-NET'), ('FAN_IN_HUB', 'TM-NET'),
    ('SANCTIONS_NEAR_MATCH', 'SCR-SAN'), ('PEP', 'SCR-PEP')
  ) AS v(INJECTED_PATTERN, RULE_ID)
)
SELECT g.INJECTED_PATTERN, e.RULE_ID,
       COUNT(DISTINCT g.CUSTOMER_ID) AS PLANTED,
       COUNT(DISTINCT IFF(a.ALERT_ID IS NOT NULL, g.CUSTOMER_ID, NULL)) AS DETECTED,
       ROUND(100 * COUNT(DISTINCT IFF(a.ALERT_ID IS NOT NULL, g.CUSTOMER_ID, NULL))
             / COUNT(DISTINCT g.CUSTOMER_ID), 0) AS RECALL_PCT
FROM CORE.GROUND_TRUTH g
JOIN expected e ON e.INJECTED_PATTERN = g.INJECTED_PATTERN
LEFT JOIN ALERTS a ON a.CUSTOMER_ID = g.CUSTOMER_ID AND a.RULE_ID = e.RULE_ID
GROUP BY g.INJECTED_PATTERN, e.RULE_ID
ORDER BY g.INJECTED_PATTERN;

-- 3. Customers per risk band (clean customers should be overwhelmingly LOW)
SELECT r.RISK_BAND,
       COUNT(*) AS CUSTOMERS,
       COUNT_IF(g.CUSTOMER_ID IS NOT NULL) AS WITH_PLANTED_PATTERN,
       COUNT_IF(g.CUSTOMER_ID IS NULL)     AS CLEAN
FROM RISK_SCORES r
LEFT JOIN (SELECT DISTINCT CUSTOMER_ID FROM CORE.GROUND_TRUTH
           WHERE INJECTED_PATTERN <> 'FALSE_POSITIVE_CONTROL') g ON g.CUSTOMER_ID = r.CUSTOMER_ID
GROUP BY r.RISK_BAND
ORDER BY MIN(r.RISK_SCORE) DESC;

-- 4. Top 15 customers with their explainable score
SELECT r.CUSTOMER_ID, c.FULL_NAME, r.PRIMARY_ACCOUNT_ID, r.RISK_SCORE, r.RISK_BAND, r.SCORE_EXPLANATION
FROM RISK_SCORES r
JOIN CORE.CUSTOMERS c ON c.CUSTOMER_ID = r.CUSTOMER_ID
ORDER BY r.RAW_SCORE DESC, r.CUSTOMER_ID
LIMIT 15;

-- 5. The demo case: why was ACC-1042 flagged?
SELECT ALERT_ID, RULE_ID, POLICY_REF, WEIGHT, REASON, EVIDENCE_TXN_IDS
FROM ALERTS
WHERE ACCOUNT_ID = 'ACC-1042'
ORDER BY WEIGHT DESC;

SELECT CUSTOMER_ID, RISK_SCORE, RISK_BAND, SCORE_EXPLANATION
FROM RISK_SCORES
WHERE PRIMARY_ACCOUNT_ID = 'ACC-1042';
