-- =============================================================================
-- TraceLedger | Layer 5 | 13_governance.sql
-- Roles, PII masking, region row-access, PII tags and an insert-only audit log.
--   TL_ANALYST          masked PII, only customers of the assigned region, can work cases
--   TL_COMPLIANCE_HEAD  full PII, all regions, approves STRs, tunes rule thresholds
--   TL_AUDITOR          masked PII, all regions, read-only (incl. the audit log)
-- Requires Enterprise edition (masking / row access policies, tags).
-- =============================================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE TRACELEDGER_WH;
USE DATABASE TRACELEDGER;

CREATE SCHEMA IF NOT EXISTS GOVERNANCE COMMENT = 'Layer 5: policies, tags and access mapping';
USE SCHEMA GOVERNANCE;

-- -----------------------------------------------------------------------------
-- 1. Roles (granted to you so you can switch between them for the demo)
-- -----------------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS TL_ANALYST         COMMENT = 'AML analyst (maker): masked PII, own region';
CREATE ROLE IF NOT EXISTS TL_COMPLIANCE_HEAD COMMENT = 'Compliance head (checker): full PII, approves STRs';
CREATE ROLE IF NOT EXISTS TL_AUDITOR         COMMENT = 'Internal audit: read-only, masked PII';

SET ME = CURRENT_USER();
GRANT ROLE TL_ANALYST         TO USER IDENTIFIER($ME);
GRANT ROLE TL_COMPLIANCE_HEAD TO USER IDENTIFIER($ME);
GRANT ROLE TL_AUDITOR         TO USER IDENTIFIER($ME);

-- Which region each analyst role may see (row access policy below reads this)
CREATE OR REPLACE TABLE REGION_ACCESS (
  ROLE_NAME  VARCHAR(60),
  REGION     VARCHAR(10)
) COMMENT = 'Region entitlements for analyst roles';
INSERT INTO REGION_ACCESS VALUES ('TL_ANALYST', 'WEST');

-- -----------------------------------------------------------------------------
-- 2. Masking policies (who sees full PII: compliance head and admins)
--    Policies check CURRENT_ROLE() (the primary role), so secondary roles in a
--    Snowsight session cannot widen access during the role-switch demo.
-- -----------------------------------------------------------------------------
CREATE MASKING POLICY IF NOT EXISTS PII_NAME_MASK AS (VAL STRING) RETURNS STRING ->
  CASE WHEN CURRENT_ROLE() IN ('TL_COMPLIANCE_HEAD', 'ACCOUNTADMIN', 'SYSADMIN') THEN VAL
       ELSE REGEXP_REPLACE(VAL, '([A-Za-z])[A-Za-z]*', '\\1***') END
  COMMENT = 'Rajesh Bhandari -> R*** B***';

CREATE MASKING POLICY IF NOT EXISTS PII_PAN_MASK AS (VAL STRING) RETURNS STRING ->
  CASE WHEN CURRENT_ROLE() IN ('TL_COMPLIANCE_HEAD', 'ACCOUNTADMIN', 'SYSADMIN') THEN VAL
       ELSE 'XXXXXX' || RIGHT(VAL, 4) END
  COMMENT = 'ABCPD1234E -> XXXXXX234E';

CREATE MASKING POLICY IF NOT EXISTS PII_PHONE_MASK AS (VAL STRING) RETURNS STRING ->
  CASE WHEN CURRENT_ROLE() IN ('TL_COMPLIANCE_HEAD', 'ACCOUNTADMIN', 'SYSADMIN') THEN VAL
       ELSE LEFT(VAL, 4) || 'XXXXXX' || RIGHT(VAL, 4) END
  COMMENT = '+91-9876543210 -> +91-XXXXXX3210';

CREATE MASKING POLICY IF NOT EXISTS PII_EMAIL_MASK AS (VAL STRING) RETURNS STRING ->
  CASE WHEN CURRENT_ROLE() IN ('TL_COMPLIANCE_HEAD', 'ACCOUNTADMIN', 'SYSADMIN') THEN VAL
       ELSE LEFT(VAL, 1) || '***@' || SPLIT_PART(VAL, '@', 2) END
  COMMENT = 'rajesh.b@example.in -> r***@example.in';

CREATE MASKING POLICY IF NOT EXISTS PII_DOB_MASK AS (VAL DATE) RETURNS DATE ->
  CASE WHEN CURRENT_ROLE() IN ('TL_COMPLIANCE_HEAD', 'ACCOUNTADMIN', 'SYSADMIN') THEN VAL
       ELSE DATE_FROM_PARTS(YEAR(VAL), 1, 1) END
  COMMENT = 'Only the birth year is visible';


ALTER TABLE CORE.CUSTOMERS MODIFY COLUMN FULL_NAME     SET MASKING POLICY PII_NAME_MASK FORCE;
ALTER TABLE CORE.CUSTOMERS MODIFY COLUMN PAN_NUMBER    SET MASKING POLICY PII_PAN_MASK FORCE;
ALTER TABLE CORE.CUSTOMERS MODIFY COLUMN PHONE         SET MASKING POLICY PII_PHONE_MASK FORCE;
ALTER TABLE CORE.CUSTOMERS MODIFY COLUMN EMAIL         SET MASKING POLICY PII_EMAIL_MASK FORCE;
ALTER TABLE CORE.CUSTOMERS MODIFY COLUMN DATE_OF_BIRTH SET MASKING POLICY PII_DOB_MASK FORCE;

-- -----------------------------------------------------------------------------
-- 3. Row access policy: analysts only see customers of their region
-- -----------------------------------------------------------------------------
ALTER TABLE CORE.CUSTOMERS DROP ALL ROW ACCESS POLICIES;

CREATE OR REPLACE ROW ACCESS POLICY REGION_RAP AS (CUSTOMER_REGION STRING) RETURNS BOOLEAN ->
  CURRENT_ROLE() IN ('TL_COMPLIANCE_HEAD', 'TL_AUDITOR', 'ACCOUNTADMIN', 'SYSADMIN')
  OR EXISTS (SELECT 1 FROM TRACELEDGER.GOVERNANCE.REGION_ACCESS m
             WHERE m.ROLE_NAME = CURRENT_ROLE() AND m.REGION = CUSTOMER_REGION)
  COMMENT = 'Analysts see only the customers of their assigned region (Policy 10.2)';

ALTER TABLE CORE.CUSTOMERS ADD ROW ACCESS POLICY REGION_RAP ON (REGION);

-- -----------------------------------------------------------------------------
-- 4. PII classification tags (visible in the catalog and in TAG_REFERENCES)
-- -----------------------------------------------------------------------------
CREATE TAG IF NOT EXISTS PII_TYPE ALLOWED_VALUES 'NAME', 'NATIONAL_ID', 'PHONE', 'EMAIL', 'DATE_OF_BIRTH'
  COMMENT = 'Personal data classification';
ALTER TABLE CORE.CUSTOMERS MODIFY COLUMN FULL_NAME     SET TAG PII_TYPE = 'NAME';
ALTER TABLE CORE.CUSTOMERS MODIFY COLUMN PAN_NUMBER    SET TAG PII_TYPE = 'NATIONAL_ID';
ALTER TABLE CORE.CUSTOMERS MODIFY COLUMN PHONE         SET TAG PII_TYPE = 'PHONE';
ALTER TABLE CORE.CUSTOMERS MODIFY COLUMN EMAIL         SET TAG PII_TYPE = 'EMAIL';
ALTER TABLE CORE.CUSTOMERS MODIFY COLUMN DATE_OF_BIRTH SET TAG PII_TYPE = 'DATE_OF_BIRTH';

-- -----------------------------------------------------------------------------
-- 5. Grants
-- -----------------------------------------------------------------------------
GRANT USAGE ON WAREHOUSE TRACELEDGER_WH TO ROLE TL_ANALYST;
GRANT USAGE ON WAREHOUSE TRACELEDGER_WH TO ROLE TL_COMPLIANCE_HEAD;
GRANT USAGE ON WAREHOUSE TRACELEDGER_WH TO ROLE TL_AUDITOR;

GRANT USAGE ON DATABASE TRACELEDGER TO ROLE TL_ANALYST;
GRANT USAGE ON DATABASE TRACELEDGER TO ROLE TL_COMPLIANCE_HEAD;
GRANT USAGE ON DATABASE TRACELEDGER TO ROLE TL_AUDITOR;
GRANT USAGE ON ALL SCHEMAS IN DATABASE TRACELEDGER TO ROLE TL_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE TRACELEDGER TO ROLE TL_COMPLIANCE_HEAD;
GRANT USAGE ON ALL SCHEMAS IN DATABASE TRACELEDGER TO ROLE TL_AUDITOR;

GRANT SELECT ON ALL TABLES IN DATABASE TRACELEDGER TO ROLE TL_ANALYST;
GRANT SELECT ON ALL TABLES IN DATABASE TRACELEDGER TO ROLE TL_COMPLIANCE_HEAD;
GRANT SELECT ON ALL TABLES IN DATABASE TRACELEDGER TO ROLE TL_AUDITOR;
GRANT SELECT ON ALL VIEWS IN DATABASE TRACELEDGER TO ROLE TL_ANALYST;
GRANT SELECT ON ALL VIEWS IN DATABASE TRACELEDGER TO ROLE TL_COMPLIANCE_HEAD;
GRANT SELECT ON ALL VIEWS IN DATABASE TRACELEDGER TO ROLE TL_AUDITOR;
GRANT SELECT ON ALL DYNAMIC TABLES IN DATABASE TRACELEDGER TO ROLE TL_ANALYST;
GRANT SELECT ON ALL DYNAMIC TABLES IN DATABASE TRACELEDGER TO ROLE TL_COMPLIANCE_HEAD;
GRANT SELECT ON ALL DYNAMIC TABLES IN DATABASE TRACELEDGER TO ROLE TL_AUDITOR;

-- Cortex AI, semantic view, search services and the copilot agent
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE TL_ANALYST;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE TL_COMPLIANCE_HEAD;
GRANT SELECT ON SEMANTIC VIEW APP.TRACELEDGER_SV TO ROLE TL_ANALYST;
GRANT SELECT ON SEMANTIC VIEW APP.TRACELEDGER_SV TO ROLE TL_COMPLIANCE_HEAD;
GRANT USAGE ON CORTEX SEARCH SERVICE APP.POLICY_SEARCH TO ROLE TL_ANALYST;
GRANT USAGE ON CORTEX SEARCH SERVICE APP.NOTES_SEARCH  TO ROLE TL_ANALYST;
GRANT USAGE ON CORTEX SEARCH SERVICE APP.MEDIA_SEARCH  TO ROLE TL_ANALYST;
GRANT USAGE ON CORTEX SEARCH SERVICE APP.POLICY_SEARCH TO ROLE TL_COMPLIANCE_HEAD;
GRANT USAGE ON CORTEX SEARCH SERVICE APP.NOTES_SEARCH  TO ROLE TL_COMPLIANCE_HEAD;
GRANT USAGE ON CORTEX SEARCH SERVICE APP.MEDIA_SEARCH  TO ROLE TL_COMPLIANCE_HEAD;
GRANT USAGE ON AGENT APP.TRACELEDGER_COPILOT TO ROLE TL_ANALYST;
GRANT USAGE ON AGENT APP.TRACELEDGER_COPILOT TO ROLE TL_COMPLIANCE_HEAD;

-- Case work: analysts and the compliance head write cases, findings and the audit log
GRANT INSERT, UPDATE ON TABLE APP.CASES         TO ROLE TL_ANALYST;
GRANT INSERT         ON TABLE APP.CASE_EVENTS   TO ROLE TL_ANALYST;
GRANT INSERT         ON TABLE APP.CASE_FINDINGS TO ROLE TL_ANALYST;
GRANT INSERT, UPDATE ON TABLE APP.CASES         TO ROLE TL_COMPLIANCE_HEAD;
GRANT INSERT         ON TABLE APP.CASE_EVENTS   TO ROLE TL_COMPLIANCE_HEAD;
GRANT INSERT, UPDATE ON TABLE APP.CASE_FINDINGS TO ROLE TL_COMPLIANCE_HEAD;   -- approve / reject
GRANT UPDATE         ON TABLE SIGNALS.RULE_PARAMS TO ROLE TL_COMPLIANCE_HEAD; -- tune thresholds
GRANT USAGE ON SEQUENCE APP.CASE_SEQ    TO ROLE TL_ANALYST;
GRANT USAGE ON SEQUENCE APP.FINDING_SEQ TO ROLE TL_ANALYST;
GRANT USAGE ON SEQUENCE APP.EVENT_SEQ   TO ROLE TL_ANALYST;
GRANT USAGE ON SEQUENCE APP.CASE_SEQ    TO ROLE TL_COMPLIANCE_HEAD;
GRANT USAGE ON SEQUENCE APP.FINDING_SEQ TO ROLE TL_COMPLIANCE_HEAD;
GRANT USAGE ON SEQUENCE APP.EVENT_SEQ   TO ROLE TL_COMPLIANCE_HEAD;

-- Audit log is insert-only: nobody but the owner can change or delete history
GRANT INSERT ON TABLE APP.AUDIT_LOG TO ROLE TL_ANALYST;
GRANT INSERT ON TABLE APP.AUDIT_LOG TO ROLE TL_COMPLIANCE_HEAD;
REVOKE UPDATE, DELETE, TRUNCATE ON TABLE APP.AUDIT_LOG FROM ROLE TL_ANALYST;
REVOKE UPDATE, DELETE, TRUNCATE ON TABLE APP.AUDIT_LOG FROM ROLE TL_COMPLIANCE_HEAD;
REVOKE UPDATE, DELETE, TRUNCATE ON TABLE APP.AUDIT_LOG FROM ROLE TL_AUDITOR;

-- Let the three roles open the app (TRACELEDGER.APP.TRACELEDGER_APP)
GRANT USAGE ON STREAMLIT APP.TRACELEDGER_APP TO ROLE TL_ANALYST;
GRANT USAGE ON STREAMLIT APP.TRACELEDGER_APP TO ROLE TL_COMPLIANCE_HEAD;
GRANT USAGE ON STREAMLIT APP.TRACELEDGER_APP TO ROLE TL_AUDITOR;

-- -----------------------------------------------------------------------------
-- 6. Proof: the same query, three roles
-- -----------------------------------------------------------------------------
USE ROLE TL_ANALYST;
SELECT 'TL_ANALYST' AS ROLE_USED, COUNT(*) AS CUSTOMERS_VISIBLE, LISTAGG(DISTINCT REGION, ',') AS REGIONS,
       MAX(IFF(CUSTOMER_ID = 'CUST-0001', FULL_NAME || ' | ' || PAN_NUMBER || ' | ' || PHONE, NULL)) AS CUST_0001
FROM TRACELEDGER.CORE.CUSTOMERS;

USE ROLE TL_AUDITOR;
SELECT 'TL_AUDITOR' AS ROLE_USED, COUNT(*) AS CUSTOMERS_VISIBLE, LISTAGG(DISTINCT REGION, ',') AS REGIONS,
       MAX(IFF(CUSTOMER_ID = 'CUST-0001', FULL_NAME || ' | ' || PAN_NUMBER || ' | ' || PHONE, NULL)) AS CUST_0001
FROM TRACELEDGER.CORE.CUSTOMERS;

USE ROLE TL_COMPLIANCE_HEAD;
SELECT 'TL_COMPLIANCE_HEAD' AS ROLE_USED, COUNT(*) AS CUSTOMERS_VISIBLE, LISTAGG(DISTINCT REGION, ',') AS REGIONS,
       MAX(IFF(CUSTOMER_ID = 'CUST-0001', FULL_NAME || ' | ' || PAN_NUMBER || ' | ' || PHONE, NULL)) AS CUST_0001
FROM TRACELEDGER.CORE.CUSTOMERS;

USE ROLE ACCOUNTADMIN;

-- Alerts still refresh with the policies in place (dynamic tables run as their owner)
ALTER DYNAMIC TABLE SIGNALS.ALERTS REFRESH;
ALTER DYNAMIC TABLE SIGNALS.RISK_SCORES REFRESH;

-- All three in one result (each line was produced by a different role above)
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID(-4)))
UNION ALL SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID(-6)))
UNION ALL SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID(-8)));
